[package]
name = "bin_crate"
version = "0.1.0"
authors = ["evil <350511976@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
