[package]
name = "csv-read"
version = "0.1.0"
authors = ["evil <350511976@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.0.5"
lazy_static = "1.1.0"